#!/bin/bash

# List of things that need patching below
# Format:

# <feature> - <repo>
#    <plugin> - <repo>

#org.eclipse.jdt - eclipse.jdt.git 
#         org.eclipse.jdt.core - eclipse.jdt.core.git 
#         org.eclipse.jdt.debug - eclipse.jdt.debug.git 
#         org.eclipse.jdt.debug.ui - eclipse.jdt.debug.git 
#         org.eclipse.jdt.launching - eclipse.jdt.debug.git 
#         org.eclipse.jdt.ui - eclipse.jdt.ui.git 
#org.eclipse.rcp - ?
#         org.eclipse.osgi - rt.equinox.framework.git 
#org.eclipse.pde - ?
#         org.eclipse.pde.api.tools - eclipse.pde.ui.git 
#         org.eclipse.pde.api.tools.ui - eclipse.pde.ui.git 

function checkout {
   if [ -a $2 ]
   then
       cd $2 ; git reset --hard HEAD ; git pull ; git status ; cd ..
   else
       git clone $1
       cd $2 ; git checkout BETA_JAVA8 ; cd ..
   fi
   if [ -a $2/pom.xml ] 
   then 
      echo Changing parent pom
      sed -i 's/>eclipse-platform-parent</>java8-eclipse-platform-parent</' $2/pom.xml
      cd $2 ; git diff ; cd ..
   fi
}

function clone {
   git clone $1
}

# for debugging purposes (use caution with this it dumps secret keys into the build log)
echo "====/home/bamboo/tools/s3.properties===="
cat /home/bamboo/tools/s3.properties
echo "====/home/bamboo/tools/s3.properties===="

#feaure repo
#clone git://git.eclipse.org/gitroot/jdt/eclipse.jdt.git

#plugin repos
checkout git://git.eclipse.org/gitroot/jdt/eclipse.jdt.core.git eclipse.jdt.core
checkout git://git.eclipse.org/gitroot/jdt/eclipse.jdt.debug.git eclipse.jdt.debug
checkout git://git.eclipse.org/gitroot/jdt/eclipse.jdt.ui.git eclipse.jdt.ui
checkout git://git.eclipse.org/gitroot/equinox/rt.equinox.framework.git rt.equinox.framework

#clone git://git.eclipse.org/gitroot/pde/eclipse.pde.git

checkout git://git.eclipse.org/gitroot/pde/eclipse.pde.ui.git eclipse.pde.ui
