#!/bin/bash

# List of things that need patching below
# Format:

# <feature> - <repo>
#    <plugin> - <repo>

#org.eclipse.jdt - eclipse.jdt.git 
#         org.eclipse.jdt.core - eclipse.jdt.core.git 
#         org.eclipse.jdt.debug - eclipse.jdt.debug.git 
#         org.eclipse.jdt.debug.ui - eclipse.jdt.debug.git 
#         org.eclipse.jdt.launching - eclipse.jdt.debug.git 
#         org.eclipse.jdt.ui - eclipse.jdt.ui.git 
#org.eclipse.rcp - ?
#         org.eclipse.osgi - rt.equinox.framework.git 
#org.eclipse.pde - ?
#         org.eclipse.pde.api.tools - eclipse.pde.ui.git 
#         org.eclipse.pde.api.tools.ui - eclipse.pde.ui.git 

function checkout {
   if [-a $2]
   then
       cd $2 ; git pull ; git status ; cd ..
   else
       git clone $1
       cd $2 ; git checkout BETA_JAVA8 ; cd ..
   fi

}

function clone {
   git clone $1
}

#feaure repo
#clone git://git.eclipse.org/gitroot/jdt/eclipse.jdt.git

#plugin repos
checkout git://git.eclipse.org/gitroot/jdt/eclipse.jdt.core.git eclipse.jdt.core
checkout git://git.eclipse.org/gitroot/jdt/eclipse.jdt.debug.git eclipse.jdt.debug
checkout git://git.eclipse.org/gitroot/jdt/eclipse.jdt.ui.git eclipse.jdt.ui
checkout git://git.eclipse.org/gitroot/equinox/rt.equinox.framework.git rt.equinox.framework

#clone git://git.eclipse.org/gitroot/pde/eclipse.pde.git

checkout git://git.eclipse.org/gitroot/pde/eclipse.pde.ui.git eclipse.pde.ui
